#Simple workflow for github Actions.

name: App push CI

on:
  push:
    branches: [ main ]

# Jobs for unit tests, APK upload to artifacts.
jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: ./gradlew testDevUnitTest --stacktrace

    build_apk:
      name: Upload APK
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Cache Gradle
            uses: actions/cache@v2
            with:
              path: ~/.gradle/caches
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
              restore-keys: |
                ${{ runner.os }}-gradle-

        - name: Setup JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Build debug APK
          run: |
            sudo chmod +x ./gradlew
                          ./gradlew :app:packageDebugUniversalApk --stacktrace

        - name: Upload to artifacts
          usues: actions/upload-artifact@v2
          with:
            name: app
            path: app/build/outputs/universal_apk/debug/app-debug-universal.apk
